---
- name: Install yum-utils
  yum:
    name: yum-utils
    state: installed
  become: yes

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: installed
  become: yes

- name: Install lvm2
  yum:
    name: lvm2
    state: installed
  become: yes

- name: Add docker-ce repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: yes

- name: Install docker-ce
  yum:
    name: docker-ce
    state: installed
  become: yes

- name: Add ansible user to docker group
  user:
    name: ansible
    groups: docker
    append: yes
  become: yes

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Insall docker pip
  command: pip install docker
  become: yes

- name: Clone AWX repository
  git:
    repo: 'https://github.com/ansible/awx.git'
    dest: /awx/
    version: devel
    clone: yes
  become: yes

- name: Start AWX deployment
  command: ansible-playbook -i inventory install.yml
  args:
    chdir: /awx/installer/
  become: yes
