---
- name: Install epel-release
  yum:
    name: epel-release
    state: installed
  become: yes

- name: Install net-tools
  yum:
    name: net-tools
    state: installed
  become: yes

- name: Install bind-utils
  yum:
    name: bind-utils
    state: installed
  become: yes

- name: Install vim
  yum:
    name: vim
    state: installed
  become: yes

- name: Install tmux
  yum:
    name: tmux
    state: installed
  become: yes

- name: Install git
  yum:
    name: git
    state: installed
  become: yes
