Vagrant.configure("2") do |config|
  config.vm.define "dc01" do |config|
		config.vm.box = "gusztavvargadr/windows-server"
  	config.vm.box_version = "1809.0.1901"
    config.vm.hostname = 'dc01'
    config.vm.network :private_network, ip: "192.168.75.10"

		config.winrm.transport = :plaintext
		config.winrm.basic_auth_only = true 

		config.vm.provision "shell", privileged: "true", powershell_elevated_interactive: "true", path: "roles/bootstrap/files/windows_default.ps1"
		config.vm.provision "shell", privileged: "true", powershell_elevated_interactive: "true", path: "roles/tools/files/windows_domain.ps1"
		config.vm.provision "reload"
		config.vm.provision "shell", privileged: "true", powershell_elevated_interactive: "true", path: "roles/tools/files/windows_domain-configure.ps1"
		config.vm.provision "shell", privileged: "true", powershell_elevated_interactive: "true", path: "roles/tools/files/windows_ca.ps1"

	config.vm.provider :virtualbox do |v|
  	#v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--name", "dc01"]
		end
  end
end

Vagrant.configure("2") do |config|
  config.vm.define "ansible01" do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = 'ansible01'
    config.vm.network :private_network, ip: "192.168.75.20"

	config.vm.provision :ansible do |ansible|
		ansible.vault_password_file = ".vault_secret.yml"
		ansible.playbook = "bootstrap_linux_default.yml"
		end

	config.vm.provision :ansible do |ansible|
		ansible.playbook = "softwares_install_linux_ansible.yml"
		end

	config.vm.provider :virtualbox do |v|
  	v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 512]
    v.customize ["modifyvm", :id, "--name", "ansible01"]
		end
  end
end

Vagrant.configure("2") do |config|
  config.vm.define "awx01", autostart: false do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = 'awx01'
    config.vm.network :private_network, ip: "192.168.75.25"

	config.vm.provision :ansible do |ansible|
		ansible.vault_password_file = ".vault_secret.yml"
		ansible.playbook = "bootstrap_linux_default.yml"
		end

	config.vm.provision :ansible do |ansible|
		ansible.playbook = "softwares_install_linux_ansible.yml"
		end

	config.vm.provision :ansible do |ansible|
		ansible.playbook = "softwares_install_linux_docker.yml"
		end

	config.vm.provider :virtualbox do |v|
  	v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 512]
    v.customize ["modifyvm", :id, "--name", "awx01"]
		end
  end
end
