Vagrant.configure("2") do |config|
  config.vm.define "ansible01" do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = 'ansible01'
    config.vm.network :private_network, ip: "192.168.75.20"

	config.vm.provision :ansible do |ansible|
		ansible.vault_password_file = ".vault_secret.yml"
		ansible.playbook = "bootstrap_linux_default.yml"
		end

	config.vm.provision :ansible do |ansible|
		ansible.playbook = "softwares_install_linux_ansible.yml"
		end

	config.vm.provider :virtualbox do |v|
  	v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 512]
    v.customize ["modifyvm", :id, "--name", "ansible01"]
		end

  config.vm.define "auth" do |config|
		config.ssh.username = "ansible"
		config.ssh.password= "ansible@123"
  	end
  end
end
